### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by uniweb31** [bootscore/bs-swiper#80] opened 2024-08-16 08:54 UTC
WP 6.6.1
bs Swipper 5.8.3
Booscore + Booscore Child : 6.0.0-beta1

[16-Aug-2024 08:52:04 UTC] PHP Fatal error:  Cannot redeclare bootscore_swiper() (previously declared in /x/x/x/x/wp-content/plugins/bs-swiper/templates/sc-swiper-card.php:42) in /x/x/x/x/wp-content/plugins/bs-swiper/templates/sc-swiper-card.php on line 174
[16-Aug-2024 08:52:04 UTC] PHP Deprecated:  Creation of dynamic property Pwf_Autoloader::$classes is deprecated in /x/x/x/x/wp-content/plugins/pwfwoofilter/includes/classes/class-pwf-autoloader.php on line 40

**Comment by crftwrk** [comment] 2024-08-16 09:27
Please describe steps to reproduce this issue in detail and share a link to your site. Try first to disable `pwfwoofilter` plugin.

**Comment by crftwrk** [comment] 2024-08-27 09:07
Closing this issue because here is no feedback.

**Closed by crftwrk** 2024-08-27 09:07 UTC
Labels: awaiting-reply
